### ISSUE TITLE
unlock/remove ipython version 5 requirement?

### ISSUE THREAD

**Issue by awkwong-whi** [conda-forge/fire-feedstock#2]
The current package requirements specify `ipython ==5` which requires ipython to be exactly 5.0.0.  But conda-forge and anaconda both have newer versions available like 5.1, 5.2, 5.3, 6.0, and 6.1.

I don't see any particular need for this package to require ipython as it can be built and run with just regular python (but ipython is nice...)

**Comment by CJ-Wright** [comment]
The code requires ipython less than 6 https://github.com/google/python-fire/blob/v0.1.1/setup.py#L33

**Comment by CJ-Wright** [comment]
As soon as the new release comes out (with the ipython requirement removed I'll gladly remove it)
PRs are also welcome!

**Comment by CJ-Wright** [comment]
#3 and #4 should have fixed this issue partially, the other pieces need a new release, so I am closing.
